<?php
if (!defined('ABSPATH')) exit;
class ELA_Question_Bank {
 public static function all(){return [
 ['She ___ from Canada.','am','is','are','be','B','A1','grammar'],['We ___ breakfast at eight.','has','have','having','had','B','A1','grammar'],
 ['The opposite of "cheap" is ___.','easy','small','expensive','early','C','A1','vocabulary'],['A person who teaches is a ___.','doctor','teacher','driver','farmer','B','A1','vocabulary'],
 ['Read: "Anna lives in Rome and works in a bank." Where does Anna live?','Paris','Rome','London','Berlin','B','A1','reading'],['Read: "Tom has a red car. His car is small." What color is it?','Blue','Green','Red','Black','C','A1','reading'],
 ['Listening: "Good morning. How are you?" What is the speaker doing?','Saying goodbye','Greeting','Ordering food','Giving directions','B','A1','listening'],['Listening: "The meeting is on Monday." When is it?','Sunday','Monday','Tuesday','Friday','B','A1','listening'],
 ['Yesterday, we ___ to the cinema.','go','goes','went','going','C','A2','grammar'],['I have lived here ___ 2022.','for','since','during','from','B','A2','grammar'],
 ['"Borrow" means to ___.','give away','take and return later','buy','break','B','A2','vocabulary'],['If a place is "crowded", it has ___.','few people','many people','no buildings','cheap food','B','A2','vocabulary'],
 ['Read: "Mark missed the bus, so he walked to work." Why did he walk?','For exercise','He missed the bus','His car broke','It rained','B','A2','reading'],['Read: "The museum is closed on Mondays but open every other day." When is it closed?','Sunday','Monday','Tuesday','Friday','B','A2','reading'],
 ['Listening: "The train leaves at half past six." What time?','5:30','6:00','6:30','7:30','C','A2','listening'],['Listening: "I ordered chicken, but they brought fish." What was ordered?','Fish','Chicken','Beef','Salad','B','A2','listening'],
 ['If I ___ enough money, I would travel more.','have','had','will have','am having','B','B1','grammar'],['She ___ her homework before she went out.','finishes','had finished','has finished','finish','B','B1','grammar'],
 ['"Reliable" describes something you can ___.','avoid','depend on','repair','ignore','B','B1','vocabulary'],['A "deadline" is the ___.','start of a project','latest time something must be done','price','meeting length','B','B1','vocabulary'],
 ['Read: "The company introduced remote work to reduce office costs." Why?','Increase travel','Reduce costs','Hire fewer people','Close the company','B','B1','reading'],['Read: "Although the restaurant was busy, we were served quickly." What happened?','Service was slow','It was empty','We were served quickly','It closed','C','B1','reading'],
 ['Listening: "My phone battery died, so I could not call." Why no call?','Forgot','Battery died','Busy','Lost number','B','B1','listening'],['Listening: "The flight has been delayed by two hours." What happened?','Cancelled','Left early','Delayed','Changed airport','C','B1','listening'],
 ['By the time we arrived, the presentation ___.','started','has started','had started','starts','C','B2','grammar'],['If they had checked the data, they ___ the error.','would notice','would have noticed','will notice','noticed','B','B2','grammar'],
 ['To "allocate" resources means to ___.','destroy them','distribute them for a purpose','hide them','replace them','B','B2','vocabulary'],['If evidence is "compelling", it is ___.','convincing','irrelevant','confusing','imaginary','A','B2','vocabulary'],
 ['Read: "Productivity increased after flexible hours were introduced, especially among experienced employees." Who benefited most?','New employees','Experienced employees','Managers','Customers','B','B2','reading'],['Read: "The proposal was rejected because its long-term benefits were uncertain." Why rejected?','Too expensive','Too short','Benefits uncertain','No budget','C','B2','reading'],
 ['Listening: "We should wait for the full-year results before drawing conclusions." What is suggested?','Decide now','Ignore data','Wait for more data','Cancel project','C','B2','listening'],['Listening: "I would have accepted it if the contract had included flexible working." Why not?','Low salary','No flexible working','Far office','Temporary job','B','B2','listening'],
 ['Had the researchers anticipated the issue, they ___ additional controls.','would introduce','would have introduced','will introduce','introduced','B','C1','grammar'],['Not only ___ the proposal costly, but it was also impractical.','was','were','is','be','A','C1','grammar'],
 ['"Ambiguous" means ___.','open to more than one interpretation','very accurate','successful','easy to verify','A','C1','vocabulary'],['To "undermine" an argument is to ___.','strengthen it','weaken its credibility','summarize it','repeat it','B','C1','vocabulary'],
 ['Read: "The author concedes that the reform has drawbacks, but maintains that long-term benefits outweigh them." What is the position?','No drawbacks','Drawbacks outweigh benefits','Benefits outweigh drawbacks','Abandon reform','C','C1','reading'],['Read: "The report stops short of claiming causation, noting only a strong correlation." What is claimed?','Causation','No relationship','Strong correlation','Weak correlation','C','C1','reading'],
 ['Listening: "I am not disputing the figures; I question the assumptions underlying them." What is questioned?','Figures','Assumptions','Date','Source','B','C1','listening'],['Listening: "The proposal is feasible in principle, provided adequate funding is secured." What is required?','More staff','Funding','Shorter timeline','Approval','B','C1','listening'],
 ['Were the premise to be false, the entire argument ___.','collapses','would collapse','would have collapsed','has collapsed','B','C2','grammar'],['No sooner ___ the results announced than concerns were raised.','were','had','have','did','B','C2','grammar'],
 ['To "mitigate" a risk is to ___.','eliminate it with certainty','reduce its impact','ignore it','create another risk','B','C2','vocabulary'],['To "corroborate" a claim is to ___.','contradict it','support it with additional evidence','simplify it','withdraw it','B','C2','vocabulary'],
 ['Read: "The ostensibly neutral account is undermined by selective omissions that privilege one interpretation." What undermines it?','Length','Selective omissions','Vocabulary','Date','B','C2','reading'],['Read: "The distinction is analytically useful, albeit somewhat artificial in practice." How is it described?','Useful but artificial','Useless','Completely objective','Impossible','A','C2','reading'],
 ['Listening: "I would hesitate to infer a causal mechanism from what is, at best, circumstantial evidence." What is advised?','Infer causation','Avoid inferring causation','Ignore evidence','Repeat experiment','B','C2','listening'],['Listening: "The apparent consensus masks substantial disagreement over the underlying assumptions." What is true?','No disagreement','Disagreement over assumptions','Everyone agrees','Consensus is genuine','B','C2','listening']
 ];}
}
