<?php
/**
 * Plugin Name: English Level Assessment
 * Description: CEFR English placement test with secure adaptive evaluation, skill scoring and saved user results.
 * Version: 0.3.0
 * Author: Ahmad Pourostami
 * License: GPL-2.0-or-later
 */
if (!defined('ABSPATH')) exit;
define('ELA_VERSION','0.3.0');
require_once __DIR__.'/includes/class-ela-db.php';
class English_Level_Assessment {
 public function __construct(){register_activation_hook(__FILE__,[$this,'activate']);add_action('admin_menu',[$this,'admin_menu']);add_action('admin_post_ela_save_question',[$this,'save_question']);add_action('admin_post_ela_delete_question',[$this,'delete_question']);add_action('wp_ajax_ela_check_answer',[$this,'check_answer']);add_action('wp_ajax_nopriv_ela_check_answer',[$this,'check_answer']);add_action('wp_ajax_ela_save_result',[$this,'save_result']);add_action('wp_ajax_nopriv_ela_save_result',[$this,'save_result']);add_shortcode('english_level_test',[$this,'shortcode']);add_action('wp_enqueue_scripts',[$this,'assets']);}
 public function activate(){global $wpdb;$table=$wpdb->prefix.'ela_questions';$charset=$wpdb->get_charset_collate();require_once ABSPATH.'wp-admin/includes/upgrade.php';dbDelta("CREATE TABLE $table (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,question TEXT NOT NULL,option_a TEXT NOT NULL,option_b TEXT NOT NULL,option_c TEXT NOT NULL,option_d TEXT NOT NULL,correct_answer CHAR(1) NOT NULL,level VARCHAR(2) NOT NULL DEFAULT 'A1',skill VARCHAR(30) NOT NULL DEFAULT 'grammar',points INT NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY level(level),KEY skill(skill)) $charset;");ELA_DB::install_results();$count=(int)$wpdb->get_var("SELECT COUNT(*) FROM $table");if(!$count)$this->seed_questions();elseif($count<12)$this->seed_advanced();}
 private function seed_questions(){global $wpdb;$t=$wpdb->prefix.'ela_questions';$qs=[['She ___ a student.','am','is','are','be','B','A1','grammar'],['I ___ coffee every morning.','drink','drinks','drank','drinking','A','A1','grammar'],['They ___ to London last year.','go','goes','went','going','C','A2','grammar'],['Rapid is closest in meaning to:','slow','quick','heavy','late','B','A2','vocabulary'],['If I had more time, I ___ another language.','learn','will learn','would learn','learned','C','B1','grammar'],['Accurate means:','correct','expensive','ancient','simple','A','B1','vocabulary'],['The report ___ by Friday.','will finish','will be finished','finished','has finish','B','B2','grammar'],['The evidence was ___ to prove his claim.','sufficient','sleepy','narrow','casual','A','B2','vocabulary']];foreach($qs as $q)$this->insert_question($q);}
 private function seed_advanced(){foreach([['Had I known about the delay, I ___ earlier.','would leave','would have left','left','will leave','B','C1','grammar'],['Her argument was nuanced, yet remarkably ___.','coherent','empty','fragile','random','A','C1','vocabulary'],['The policy is intended to ___ the negative effects of inflation.','mitigate','imitate','compile','allocate','A','C2','vocabulary'],['Were the findings independently verified, the claim ___ considerably stronger.','is','would be','will be','has been','B','C2','grammar']] as $q)$this->insert_question($q);}
 private function insert_question($q){global $wpdb;$wpdb->insert($wpdb->prefix.'ela_questions',['question'=>$q[0],'option_a'=>$q[1],'option_b'=>$q[2],'option_c'=>$q[3],'option_d'=>$q[4],'correct_answer'=>$q[5],'level'=>$q[6],'skill'=>$q[7]]);}
 public function admin_menu(){add_menu_page('English Level','English Level','manage_options','ela-questions',[$this,'admin_page'],'dashicons-welcome-learn-more');}
 public function admin_page(){if(!current_user_can('manage_options'))return;global $wpdb;$qs=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}ela_questions ORDER BY id DESC");$results=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}ela_results ORDER BY id DESC LIMIT 50");?><div class="wrap"><h1>English Level Assessment</h1><p>شورت‌کد آزمون: <code>[english_level_test]</code></p><h2>افزودن سؤال</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="ela_save_question"><?php wp_nonce_field('ela_save_question'); ?><p><textarea name="question" rows="2" class="large-text" placeholder="Question" required></textarea></p><p><input name="option_a" placeholder="A" required> <input name="option_b" placeholder="B" required> <input name="option_c" placeholder="C" required> <input name="option_d" placeholder="D" required></p><p>Correct <select name="correct_answer"><option>A</option><option>B</option><option>C</option><option>D</option></select> Level <select name="level"><?php foreach(['A1','A2','B1','B2','C1','C2'] as $l)echo '<option>'.$l.'</option>';?></select> Skill <select name="skill"><?php foreach(['grammar','vocabulary','reading','listening'] as $s)echo '<option>'.$s.'</option>';?></select></p><?php submit_button('Add Question'); ?></form><h2>Questions</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Question</th><th>Level</th><th>Skill</th><th>Action</th></tr></thead><tbody><?php foreach($qs as $q):?><tr><td><?php echo(int)$q->id;?></td><td><?php echo esc_html($q->question);?></td><td><?php echo esc_html($q->level);?></td><td><?php echo esc_html($q->skill);?></td><td><a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=ela_delete_question&id='.$q->id),'ela_delete_'.$q->id));?>">Delete</a></td></tr><?php endforeach;?></tbody></table><h2>Latest Results</h2><table class="widefat striped"><thead><tr><th>User</th><th>Score</th><th>Level</th><th>Date</th></tr></thead><tbody><?php foreach($results as $r):?><tr><td><?php echo$r->user_id?(int)$r->user_id:'Guest';?></td><td><?php echo(int)$r->score;?>%</td><td><?php echo esc_html($r->level);?></td><td><?php echo esc_html($r->created_at);?></td></tr><?php endforeach;?></tbody></table></div><?php}
 public function save_question(){if(!current_user_can('manage_options')||!check_admin_referer('ela_save_question'))wp_die('Unauthorized');global $wpdb;$wpdb->insert($wpdb->prefix.'ela_questions',['question'=>sanitize_textarea_field(wp_unslash($_POST['question']??'')),'option_a'=>sanitize_text_field(wp_unslash($_POST['option_a']??'')),'option_b'=>sanitize_text_field(wp_unslash($_POST['option_b']??'')),'option_c'=>sanitize_text_field(wp_unslash($_POST['option_c']??'')),'option_d'=>sanitize_text_field(wp_unslash($_POST['option_d']??'')),'correct_answer'=>sanitize_text_field(wp_unslash($_POST['correct_answer']??'A')),'level'=>sanitize_text_field(wp_unslash($_POST['level']??'A1')),'skill'=>sanitize_text_field(wp_unslash($_POST['skill']??'grammar'))]);wp_safe_redirect(admin_url('admin.php?page=ela-questions'));exit;}
 public function delete_question(){ $id=absint($_GET['id']??0);if(!current_user_can('manage_options')||!$id||!wp_verify_nonce($_GET['_wpnonce']??'','ela_delete_'.$id))wp_die('Unauthorized');global $wpdb;$wpdb->delete($wpdb->prefix.'ela_questions',['id'=>$id]);wp_safe_redirect(admin_url('admin.php?page=ela-questions'));exit;}
 public function check_answer(){check_ajax_referer('ela_result','nonce');global $wpdb;$id=absint($_POST['question_id']??0);$choice=strtoupper(sanitize_text_field(wp_unslash($_POST['answer']??'')));if(!$id||!in_array($choice,['A','B','C','D'],true))wp_send_json_error(['message'=>'Invalid answer.'],400);$q=$wpdb->get_row($wpdb->prepare("SELECT id,correct_answer,level,skill FROM {$wpdb->prefix}ela_questions WHERE id=%d",$id));if(!$q)wp_send_json_error(['message'=>'Question not found.'],404);wp_send_json_success(['correct'=>hash_equals($q->correct_answer,$choice),'level'=>$q->level,'skill'=>$q->skill]);}
 public function save_result(){check_ajax_referer('ela_result','nonce');$score=max(0,min(100,(int)($_POST['score']??0)));$level=sanitize_text_field(wp_unslash($_POST['level']??'A1'));$skills=isset($_POST['skills'])?json_decode(wp_unslash($_POST['skills']),true):[];ELA_DB::save_result(get_current_user_id(),$score,$level,is_array($skills)?$skills:[]);wp_send_json_success();}
 public function assets(){if(!is_singular())return;global $post;if($post&&has_shortcode($post->post_content,'english_level_test')){wp_enqueue_style('ela-style',plugins_url('assets/style.css',__FILE__),[],ELA_VERSION);wp_enqueue_script('ela-script',plugins_url('assets/app.js',__FILE__),[],ELA_VERSION,true);wp_localize_script('ela-script','ELA_CONFIG',['ajax_url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('ela_result')]);}}
 public function shortcode(){global $wpdb;$questions=$wpdb->get_results("SELECT * FROM {$wpdb->prefix}ela_questions ORDER BY FIELD(level,'A1','A2','B1','B2','C1','C2'),id ASC");if(!$questions)return '<p>No questions available.</p>';ob_start();?><div id="ela-test" class="ela-test" dir="ltr"><div class="ela-progress"><span id="ela-progress-bar"></span></div><div id="ela-question-wrap"></div><button type="button" id="ela-next">Next</button><div id="ela-result" hidden></div></div><script>window.ELA_QUESTIONS=<?php echo wp_json_encode(array_map(function($q){return ['id'=>(int)$q->id,'question'=>$q->question,'options'=>['A'=>$q->option_a,'B'=>$q->option_b,'C'=>$q->option_c,'D'=>$q->option_d],'level'=>$q->level,'skill'=>$q->skill];},$questions));?>;</script><?php return ob_get_clean();}
}
new English_Level_Assessment();
